import { BoatModel, Distributor, Accessory, StoreProduct } from "./types";

export const boatModels: BoatModel[] = [
  /* ────────────── LINEA 150 ────────────── */
  {
    id: "vision-150-eco",
    slug: "vision-150-eco",
    name: "Visión 150 Eco",
    tagline: "Compacta, versátil y accesible",
    description:
      "La Visión 150 Eco es la embarcación ideal para quienes buscan iniciarse en la navegación con un producto de calidad. Compacta y eficiente, perfecta para ríos y lagos.",
    category: "15-pies",
    specs: {
      eslora: "4,56 m",
      manga: "1,82 m",
      puntal: "0,91 m",
      calado: "0,35 m",
      capacidad: 5,
      motorizacion: "40 – 70 HP",
      combustible: "25 Litros",
      uso: "Recreación y Paseo",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Tapicería náutica con UV",
      "Dos butacas giratorias",
      "Parabrisas curvo",
      "Botazo PVC",
      "Guantera con cerradura",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v150-eco-2.jpeg",
      "/images/modelos/v150-eco-3.jpeg",
      "/images/modelos/v150-eco-4.jpeg",
    ],
    heroImage: "/images/modelos/v150-eco-2.jpeg",
  },
  {
    id: "vision-150-xl",
    slug: "vision-150-xl",
    name: "Visión 150 XL",
    tagline: "Mayor espacio, misma agilidad",
    description:
      "La Visión 150 XL ofrece más espacio interior manteniendo la agilidad y eficiencia que caracterizan a la línea 150. Incluye bimini, tonneau de proa y más equipamiento de serie.",
    category: "15-pies",
    specs: {
      eslora: "4,56 m",
      manga: "1,82 m",
      puntal: "0,91 m",
      calado: "0,35 m",
      capacidad: 5,
      motorizacion: "40 – 70 HP",
      combustible: "25 Litros",
      uso: "Recreación y Paseo",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Escalera de popa tres escalones",
      "Cuatro posa vasos inox",
      "Cinco manijas de sujeción inox",
      "Tapicería náutica con UV",
      "Dos butacas giratorias o dos Back to Back",
      "Parabrisas curvo",
      "Tonneau de proa",
      "Bimini",
      "Botazo PVC",
      "Guantera con cerradura",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v150-xl-2.jpeg",
      "/images/modelos/v150-xl-3.jpeg",
      "/images/modelos/v150-xl-4.jpeg",
    ],
    heroImage: "/images/modelos/v150-xl-2.jpeg",
  },

  /* ────────────── LINEA 165 ────────────── */
  {
    id: "vision-165",
    slug: "vision-165",
    name: "Visión 165",
    tagline: "Equilibrio perfecto para toda la familia",
    description:
      "La Visión 165 es el punto medio ideal: suficiente espacio para disfrutar en familia con una motorización que permite versatilidad tanto en ríos como en mar abierto.",
    category: "15-pies",
    specs: {
      eslora: "5,26 m",
      manga: "2,08 m",
      puntal: "1,01 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "70 – 115 HP",
      combustible: "65 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Escalera de popa tres escalones",
      "Cinco posa vasos de plástico",
      "Tapicería náutica con UV",
      "Dos butacas giratorias o dos Back to Back",
      "Parabrisas curvo",
      "Botazo PVC",
      "Mesa matrizada en popa",
      "Conservadora matrizada",
      "Dos posa cañas de plástico",
      "Guarda esquíes",
      "Tanque de combustible, toma externa",
      "Medidor de combustible",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v165-2.jpeg",
      "/images/modelos/v165-3.jpeg",
      "/images/modelos/v165-4.jpeg",
    ],
    heroImage: "/images/modelos/v165-2.jpeg",
  },

  /* ────────────── LINEA 180 ────────────── */
  {
    id: "vision-180-freedom",
    slug: "vision-180-freedom",
    name: "Visión 180 Freedom",
    tagline: "Libertad sobre el agua",
    description:
      "La Visión 180 Freedom combina diseño deportivo con una distribución interior pensada para el máximo confort. Navegá con total libertad y estilo.",
    category: "18-pies",
    specs: {
      eslora: "5,60 m",
      manga: "2,08 m",
      puntal: "1,01 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "90 – 150 HP",
      combustible: "107 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Escalera de popa tres escalones",
      "Tapicería náutica con UV",
      "Dos butacas giratorias o dos Back to Back",
      "Parabrisas curvo",
      "Botazo PVC",
      "Conservadora matrizada",
      "Guarda esquíes",
      "Tanque de combustible, toma externa",
      "Medidor de combustible",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v180-freedom-9.png",
      "/images/modelos/v180-freedom-8.jpeg",
    ],
    heroImage: "/images/modelos/v180-freedom-9.png",
  },
  {
    id: "vision-180-sport",
    slug: "vision-180-sport",
    name: "Visión 180 Sport",
    tagline: "Deportividad pura",
    description:
      "La Visión 180 Sport está diseñada para quienes buscan adrenalina. Con líneas deportivas agresivas y motorización potente, cada salida es una experiencia única.",
    category: "18-pies",
    specs: {
      eslora: "5,26 m",
      manga: "2,08 m",
      puntal: "1,01 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "90 – 150 HP",
      combustible: "107 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Escalera de popa tres escalones",
      "Tres posa vasos de plástico",
      "Seis manijas de sujeción inox",
      "Tapicería náutica con UV",
      "Dos butacas giratorias o dos Back to Back",
      "Parabrisas curvo",
      "Botazo PVC",
      "Conservadora matrizada",
      "Dos posa cañas plástico",
      "Guarda esquíes",
      "Tanque de combustible, toma externa",
      "Medidor de combustible",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v180-sport-2.jpeg",
      "/images/modelos/v180-sport-3.jpeg",
      "/images/modelos/v180-sport-4.jpeg",
    ],
    heroImage: "/images/modelos/v180-sport-2.jpeg",
  },
  {
    id: "vision-180-deluxe",
    slug: "vision-180-deluxe",
    name: "Visión 180 Deluxe",
    tagline: "El lujo de la línea 180",
    description:
      "La Visión 180 Deluxe es la versión más equipada y refinada de la línea 180. Acabados premium con bimini, tonneau, planchadas y botazo inox de serie.",
    category: "18-pies",
    specs: {
      eslora: "5,60 m",
      manga: "2,08 m",
      puntal: "1,01 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "90 – 150 HP",
      combustible: "107 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas inox",
      "Escalera de popa tres escalones",
      "Tres posa vasos inox",
      "Cinco manijas de sujeción inox",
      "Tapicería náutica con UV",
      "Dos butacas giratorias o dos Back to Back",
      "Parabrisas curvo",
      "Tonneau de proa",
      "Bimini",
      "Botazo inox",
      "Conservadora matrizada",
      "Dos posa cañas",
      "Guarda esquíes",
      "Tanque de combustible, toma externa",
      "Medidor de combustible",
      "Planchadas",
      "Guantera con cerradura",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v180-deluxe-1.jpeg",
      "/images/modelos/v180-deluxe-2.jpeg",
      "/images/modelos/v180-deluxe-3.jpeg",
    ],
    heroImage: "/images/modelos/v180-deluxe-1.jpeg",
  },

  /* ────────────── LINEA 195 BOSS ────────────── */
  {
    id: "vision-195-boss-st",
    slug: "vision-195-boss-st",
    name: "Visión 195 Boss ST",
    tagline: "El nuevo estándar en lanchas medianas",
    description:
      "La Visión 195 Boss ST establece un nuevo estándar con amplio espacio interior, manga de 2,54 m y motorización de hasta 250 HP. Equipamiento completo de serie.",
    category: "20-pies",
    specs: {
      eslora: "5,89 m",
      manga: "2,54 m",
      puntal: "1,40 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "130 – 250 HP",
      combustible: "100 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Luces de cortesía",
      "Bomba de achique 2000gph",
      "Un toma 12v y dos USB",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Seis cornamusas inox",
      "Escalera de popa tres escalones",
      "Seis posa vasos plástico",
      "Manijas de sujeción inox",
      "Botazo de inox",
      "Tapicería náutica con UV",
      "Espacio para conservadora",
      "Amplios espacios de guardado",
      "Dos posa cañas inox",
      "Dos butacas giratorias",
      "Guarda esquíes",
      "Guanteras laterales",
      "Tanque de combustible",
      "Sensor de combustible",
      "Estéreo náutico con dos parlantes",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v195-boss-st-1.jpeg",
      "/images/modelos/v195-boss-st-2.jpeg",
      "/images/modelos/v195-boss-st-3.jpeg",
    ],
    heroImage: "/images/modelos/v195-boss-st-1.jpeg",
  },
  {
    id: "vision-195-boss-ex",
    slug: "vision-195-boss-ex",
    name: "Visión 195 Boss EX",
    tagline: "Equipamiento Extreme de serie",
    description:
      "La Visión 195 Boss EX es la versión Extreme de la línea 195 Boss. Incluye estéreo con cuatro parlantes, revestimiento de piso y ecosonda de serie.",
    category: "20-pies",
    isNew: true,
    specs: {
      eslora: "5,89 m",
      manga: "2,54 m",
      puntal: "1,40 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "130 – 250 HP",
      combustible: "100 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Luces de cortesía",
      "Bomba de achique 2000gph",
      "Un toma 12v y dos USB",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Seis cornamusas inox",
      "Escalera de popa tres escalones",
      "Seis posa vasos plástico",
      "Manijas de sujeción inox",
      "Botazo de inox",
      "Tapicería náutica con UV",
      "Mesa de quita y pon en popa",
      "Espacio para conservadora",
      "Amplios espacios de guardado",
      "Dos posa cañas inox",
      "Dos butacas giratorias",
      "Guarda esquíes",
      "Guanteras laterales",
      "Tanque de combustible",
      "Sensor de combustible",
      "Estéreo náutico con cuatro parlantes",
      "Revestimiento de piso (alfombra/goma)",
      "Ecosonda",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v195-boss-ex-1.jpeg",
      "/images/modelos/v195-boss-ex-2.jpeg",
      "/images/modelos/v195-boss-ex-3.jpeg",
    ],
    heroImage: "/images/modelos/v195-boss-ex-1.jpeg",
  },

  /* ────────────── LINEA 200 ────────────── */
  {
    id: "vision-200",
    slug: "vision-200",
    name: "Visión 200",
    tagline: "Potencia y presencia",
    description:
      "La Visión 200 lleva la experiencia náutica a otro nivel. Con espacios generosos y motorización de hasta 250 HP, es la embarcación que marca la diferencia.",
    category: "20-pies",
    specs: {
      eslora: "6,00 m",
      manga: "2,20 m",
      puntal: "1,47 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "130 – 250 HP",
      combustible: "137 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas delta inox",
      "Escalera de popa tres escalones",
      "Posa vasos plástico",
      "Tapicería náutica con UV",
      "Dos butacas giratorias",
      "Guantera con cerradura",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v200-1.jpeg",
      "/images/modelos/v200-2.jpeg",
      "/images/modelos/v200-3.jpeg",
    ],
    heroImage: "/images/modelos/v200-1.jpeg",
  },
  {
    id: "vision-200-sport",
    slug: "vision-200-sport",
    name: "Visión 200 Sport",
    tagline: "Tope de gama deportivo",
    description:
      "La Visión 200 Sport es diseño deportivo puro. Líneas agresivas, motorización de hasta 250 HP y equipamiento completo de serie.",
    category: "20-pies",
    specs: {
      eslora: "6,00 m",
      manga: "2,20 m",
      puntal: "1,47 m",
      calado: "0,35 m",
      capacidad: 8,
      motorizacion: "130 – 250 HP",
      combustible: "137 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Bomba de achique 2000gph",
      "Un toma 12v",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Cuatro cornamusas delta inox",
      "Escalera de popa tres escalones",
      "Posa vasos plástico",
      "Tapicería náutica con UV",
      "Dos butacas giratorias",
      "Guantera con cerradura",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v200-sport-1.jpeg",
      "/images/modelos/v200-sport-2.jpeg",
      "/images/modelos/v200-sport-3.jpeg",
    ],
    heroImage: "/images/modelos/v200-sport-1.jpeg",
  },

  /* ────────────── LINEA 212 BOSS ────────────── */
  {
    id: "vision-212-boss-st",
    slug: "vision-212-boss-st",
    name: "Visión 212 Boss ST",
    tagline: "Imponente presencia en el agua",
    description:
      "La Visión 212 Boss ST es nuestra embarcación de gran porte con motorización de hasta 400 HP. Espacio para 10 personas y equipamiento completo.",
    category: "20-pies",
    specs: {
      eslora: "6,46 m",
      manga: "2,48 m",
      puntal: "1,44 m",
      calado: "0,60 m",
      capacidad: 10,
      motorizacion: "200 – 400 HP",
      combustible: "160 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Luces de cortesía",
      "Bomba de achique 2000gph",
      "Un toma 12v y dos USB",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Seis cornamusas embutibles inox",
      "Escalera de proa tres escalones",
      "Escalera de popa tres escalones",
      "Seis posa vasos inox",
      "Manijas de sujeción inox",
      "Tapicería náutica con UV",
      "Butaca giratoria timonel",
      "Asiento en L con respaldo móvil en popa",
      "Tambucho guarda ancla en proa",
      "Tambucho guarda esquíes",
      "Tres conservadoras matrizadas",
      "Tonneau de proa",
      "Bimini",
      "Botazo inox",
      "Solarium en proa",
      "Estéreo náutico con dos parlantes",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v212-boss-st-1.jpeg",
      "/images/modelos/v212-boss-st-2.jpeg",
      "/images/modelos/v212-boss-st-4.jpeg",
    ],
    heroImage: "/images/modelos/v212-boss-st-1.jpeg",
  },
  {
    id: "vision-212-boss-ex",
    slug: "vision-212-boss-ex",
    name: "Visión 212 Boss EX",
    tagline: "Extreme sin compromisos",
    description:
      "La Visión 212 Boss EX es la versión Extreme del buque insignia. Todo el equipamiento de la ST más revestimiento de piso, ecosonda y estéreo premium de serie.",
    category: "20-pies",
    isNew: true,
    specs: {
      eslora: "6,46 m",
      manga: "2,48 m",
      puntal: "1,44 m",
      calado: "0,60 m",
      capacidad: 10,
      motorizacion: "200 – 400 HP",
      combustible: "160 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Equipo de dirección dependiendo del motor",
      "Volante de cuero",
      "Parabrisas curvo",
      "Luces de navegación y fondeo",
      "Luces de cortesía",
      "Bomba de achique 2000gph",
      "Un toma 12v y dos USB",
      "Caja de batería",
      "Corte de batería",
      "Instalación eléctrica ignífuga homologada",
      "Tres cáncamos de amarre 3/8\" inox",
      "Seis cornamusas embutibles inox",
      "Escalera de proa tres escalones",
      "Escalera de popa tres escalones",
      "Seis posa vasos inox",
      "Manijas de sujeción inox",
      "Tapicería náutica con UV",
      "Butaca giratoria timonel",
      "Asiento en L con respaldo móvil en popa",
      "Tambucho guarda ancla en proa",
      "Tambucho guarda esquíes",
      "Tres conservadoras matrizadas",
      "Tonneau de proa",
      "Bimini",
      "Botazo inox",
      "Solarium en proa",
      "Estéreo náutico con cuatro parlantes",
      "Revestimiento de piso (alfombra/goma)",
      "Ecosonda",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v212-boss-ex-1.jpeg",
      "/images/modelos/v212-boss-ex-2.jpeg",
      "/images/modelos/v212-boss-ex-4.jpeg",
    ],
    heroImage: "/images/modelos/v212-boss-ex-1.jpeg",
  },
  {
    id: "vision-212-boss-st-wc",
    slug: "vision-212-boss-st-wc",
    name: "Visión 212 Boss ST WC",
    tagline: "Gran porte con baño privado",
    description:
      "La Visión 212 Boss ST WC suma un baño compartimentado con inodoro químico portátil al equipamiento completo de la línea 212 Boss. Ideal para navegación prolongada.",
    category: "20-pies",
    specs: {
      eslora: "6,46 m",
      manga: "2,48 m",
      puntal: "1,44 m",
      calado: "0,60 m",
      capacidad: 10,
      motorizacion: "200 – 400 HP",
      combustible: "160 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Todo el equipamiento ST",
      "Baño compartimentado",
      "Inodoro químico portátil",
      "Ojo de buey con ventilación en baño",
      "Luz interior",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v212-boss-st-wc-1.jpeg",
      "/images/modelos/v212-boss-st-wc-2.jpeg",
      "/images/modelos/v212-boss-st-wc-4.jpeg",
    ],
    heroImage: "/images/modelos/v212-boss-st-wc-1.jpeg",
  },
  {
    id: "vision-212-boss-ex-wc",
    slug: "vision-212-boss-ex-wc",
    name: "Visión 212 Boss EX WC",
    tagline: "La máxima expresión de Astillero Visión",
    description:
      "La Visión 212 Boss EX WC es el tope absoluto de la línea. Combina el equipamiento Extreme con baño privado. La embarcación más completa de nuestro catálogo.",
    category: "20-pies",
    isNew: true,
    specs: {
      eslora: "6,46 m",
      manga: "2,48 m",
      puntal: "1,44 m",
      calado: "0,60 m",
      capacidad: 10,
      motorizacion: "200 – 400 HP",
      combustible: "160 Litros",
      uso: "Deportivo y Placer",
      material: "P.R.F.V.",
    },
    equipment: [
      "Todo el equipamiento EX",
      "Baño compartimentado",
      "Inodoro químico portátil",
      "Ojo de buey con ventilación en baño",
      "Luz interior",
    ],
    colors: ["Blanco", "Azul", "Gris", "Negro", "Rojo"],
    images: [
      "/images/modelos/v212-boss-ex-wc-1.jpeg",
      "/images/modelos/v212-boss-ex-wc-2.jpeg",
      "/images/modelos/v212-boss-ex-wc-4.jpeg",
    ],
    heroImage: "/images/modelos/v212-boss-ex-wc-1.jpeg",
  },
];

export const distributors: Distributor[] = [
  { id: "d1", name: "Arena Náutica", address: "Av. del Libertador 18.090, San Isidro", province: "Buenos Aires", phone: "15-2525-1000" },
  { id: "d2", name: "Náutica Pinilla", address: "Mendoza 5680 Oeste", province: "Santa Fe", phone: "0341 456-6125" },
  { id: "d3", name: "Delfín Náutica S.A.", address: "Av. Leando N. Alem 3190", province: "Santa Fe", phone: "0342-4562232" },
  { id: "d4", name: "Roca Marine", address: "Brasil 926, General Roca", province: "Río Negro", phone: "298 450-4207" },
  { id: "d5", name: "Patagonia Marine", address: "Monteverde 1241, Bariloche", province: "Río Negro", phone: "0294 492-3322" },
  { id: "d6", name: "Petri", address: "Vitelmo Carabajal 110, Arrecifes", province: "Buenos Aires", phone: "247 845-3789" },
  { id: "d7", name: "Motonáutica", address: "Alvear 478, Monte Caseros", province: "Corrientes", phone: "377 442-1822" },
  { id: "d8", name: "Náutica Daniela", address: "Ruta 9 Nro 3626, Reconquista", province: "Santa Fe", phone: "348 221-9198" },
  { id: "d9", name: "Estilo Náutica S.R.L.", address: "Av. Uruguay 5893, Posadas", province: "Misiones", phone: "376 445-1517" },
  { id: "d10", name: "Náutica UNO", address: "Avellaneda Bis 886, Rosario", province: "Santa Fe", phone: "034 1309-0985" },
  { id: "d11", name: "Náutica Del Puerto", address: "Av. Del Valle 337, Gualeguaychú", province: "Entre Ríos", phone: "034 4654-5763" },
  { id: "d12", name: "Antonio Motos", address: "Sarmiento 1001, Villa Ocampo", province: "Santa Fe", phone: "348 264-1306" },
  { id: "d13", name: "Náutica Fam", address: "Av. Independencia 4246, Corrientes Capital", province: "Corrientes", phone: "379 468-3776" },
  { id: "d14", name: "Náutica Becares", address: "Acceso Sur 831, Godoy Cruz", province: "Mendoza", phone: "261 417-4751" },
  { id: "d15", name: "Scheller y Cia", address: "Mariano Losa 97, Goya", province: "Corrientes", phone: "377 742-1925" },
];

export const accessories: Accessory[] = [
  { id: "a1", name: "Barra de Ski / Torre Wake", description: "Barra de acero inoxidable para esquí náutico", category: "accesorios" },
  { id: "a2", name: "Ecosonda", description: "Sistema de ecosonda para detección de profundidad", category: "accesorios" },
  { id: "a3", name: "VHF", description: "Radio transmisor marino VHF", category: "accesorios" },
  { id: "a4", name: "Mesa de Quita y Pon", description: "Mesa desmontable para cockpit", category: "accesorios" },
  { id: "a5", name: "Cerramiento", description: "Cerramiento completo para navegación en días fríos", category: "accesorios" },
  { id: "a6", name: "Revestimiento de Piso", description: "Alfombra o goma antideslizante premium", category: "accesorios" },
  { id: "a7", name: "Luces de Cortesía", description: "Iluminación LED de cortesía interior", category: "accesorios" },
  { id: "a8", name: "Solarium", description: "Solarium para tomar sol en proa", category: "accesorios" },
  { id: "a9", name: "Estéreo Náutico", description: "Sistema de audio marino con parlantes", category: "accesorios" },
  { id: "a10", name: "Instalaciones", description: "Instalación profesional de accesorios y equipamiento", category: "servicios" },
  { id: "a11", name: "Reparaciones", description: "Servicio de reparación de casco y estructura", category: "servicios" },
  { id: "a12", name: "Lonas", description: "Confección de lonas a medida para tu embarcación", category: "servicios" },
  { id: "a13", name: "Adicionales", description: "Personalización y adicionales a medida", category: "servicios" },
];

export const CONTACT_INFO = {
  address: "Río Luján 1151, San Fernando, Buenos Aires, Argentina",
  email: "info@astillerovision.com.ar",
  phone: "+54 (9) 11 3069-1955",
  whatsapp: "5491130691955",
  instagram: "https://www.instagram.com/astillerovision/",
  facebook: "https://www.facebook.com/astillerovision/",
};

export const storeProducts: StoreProduct[] = [
  /* ────────── REPUESTOS ────────── */
  { id: "r1", name: "Hélice de Aluminio 3 Palas", description: "Hélice de aluminio de alta resistencia para motores de 40 a 115 HP. Paso 13.", price: 185000, category: "repuestos", image: "/images/store/helice.webp" },
  { id: "r2", name: "Filtro de Combustible Marino", description: "Filtro separador de agua y combustible. Compatible con motores Mercury y Yamaha.", price: 42000, category: "repuestos", image: "/images/store/filtro.webp" },
  { id: "r3", name: "Kit de Bujías NGK Marina", description: "Set de 4 bujías NGK especiales para motores fuera de borda de 4 tiempos.", price: 38500, category: "repuestos", image: "/images/store/bujias.webp" },
  { id: "r4", name: "Ánodo de Zinc Anti-corrosión", description: "Ánodo de sacrificio para protección catódica del motor y cola.", price: 18000, category: "repuestos", image: "/images/store/anodo.webp" },
  { id: "r5", name: "Aceite Náutico 4T 10W-30", description: "Aceite sintético premium para motores marinos de 4 tiempos. Bidón 4 litros.", price: 65000, category: "repuestos", image: "/images/store/aceite.webp" },
  { id: "r6", name: "Bomba de Achique 2000 GPH", description: "Bomba de achique automática de alto caudal, 12V. Instalación sumergible.", price: 95000, category: "repuestos", image: "/images/store/bomba.webp" },
  /* ────────── MOTORES ────────── */
  { id: "m1", name: "Mercury 60 HP 4T EFI", description: "Motor fuera de borda Mercury 60 HP, 4 tiempos, inyección electrónica. Arranque eléctrico.", price: 12500000, category: "motores", image: "/images/store/mercury60.webp", badge: "Popular" },
  { id: "m2", name: "Yamaha 90 HP 4T", description: "Motor Yamaha F90, 4 tiempos, confiabilidad y rendimiento superior. Ideal para lanchas de 15-18 pies.", price: 18900000, category: "motores", image: "/images/store/yamaha90.webp" },
  { id: "m3", name: "Mercury 115 HP 4T EFI CT", description: "Motor Mercury 115 HP Command Thrust. Máxima potencia para embarcaciones de 18-21 pies.", price: 24500000, category: "motores", image: "/images/store/mercury115.webp", badge: "Top" },
  { id: "m4", name: "Evinrude E-TEC 75 HP", description: "Motor E-TEC 2 tiempos de inyección directa. Bajo consumo y mantenimiento reducido.", price: 14200000, category: "motores", image: "/images/store/evinrude75.webp" },
  { id: "m5", name: "Mercury 200 HP V6 Verado", description: "Motor Mercury Verado 200 HP, V6 supercargado. La máxima expresión en potencia marina.", price: 42000000, category: "motores", image: "/images/store/mercury200.webp", badge: "Premium" },
  /* ────────── ACCESORIOS ────────── */
  { id: "ac1", name: "Ecosonda Garmin Striker 4", description: "Ecosonda con GPS integrado, pantalla color 4.3\". Transductor incluido.", price: 320000, category: "accesorios", image: "/images/store/ecosonda.webp" },
  { id: "ac2", name: "Radio VHF Marino Uniden", description: "Radio VHF marina 25W con DSC integrado. Resistente al agua IPX7.", price: 185000, category: "accesorios", image: "/images/store/vhf.webp" },
  { id: "ac3", name: "Barra de Ski Inoxidable", description: "Barra de esquí de acero inoxidable pulido. Instalación sobre espejo de popa.", price: 280000, category: "accesorios", image: "/images/store/barra-ski.webp" },
  { id: "ac4", name: "Solarium de Proa Premium", description: "Solarium tapizado en náutica UV con relleno de alta densidad. A medida.", price: 450000, category: "accesorios", image: "/images/store/solarium.webp", badge: "A medida" },
  { id: "ac5", name: "Estéreo Marino Bluetooth", description: "Sistema de audio marino con Bluetooth, USB y parlantes 6.5\" resistentes al agua.", price: 195000, category: "accesorios", image: "/images/store/estereo.webp" },
  /* ────────── SERVICIOS ────────── */
  { id: "s1", name: "Service Completo de Motor", description: "Cambio de aceite, filtros, bujías, revisión de sistemas eléctricos y de combustible.", price: 250000, category: "servicios", image: "/images/store/service.webp" },
  { id: "s2", name: "Pintura y Gelcoat", description: "Reparación y pintura de casco con gelcoat náutico. Incluye pulido final.", price: 480000, category: "servicios", image: "/images/store/pintura.webp" },
  { id: "s3", name: "Pulido y Encerado", description: "Pulido integral del casco y encerado con protección UV. Deja como nuevo.", price: 180000, category: "servicios", image: "/images/store/pulido.webp" },
  { id: "s4", name: "Tapizado Náutico Completo", description: "Retapizado integral con material náutico UV de primera calidad. Incluye butacas.", price: 650000, category: "servicios", image: "/images/store/tapizado.webp", badge: "Más pedido" },
];
